"""add source documents

Revision ID: 11652bad36b2
Revises: 397a918bcc44
Create Date: 2026-09-25 11:02:42.536314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11652bad36b2'
down_revision: Union[str, None] = '397a918bcc44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('stored_path', sa.String(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sha256')
    )
    op.add_column('daily_entries', sa.Column('source_document_id', sa.Integer(), nullable=True))
    op.create_foreign_key('daily_entries_source_document_id_fkey', 'daily_entries', 'source_documents', ['source_document_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('daily_entries_source_document_id_fkey', 'daily_entries', type_='foreignkey')
    op.drop_column('daily_entries', 'source_document_id')
    op.drop_table('source_documents')
    # ### end Alembic commands ###
