"""initial schema

Revision ID: aff938d3e38b
Revises: 
Create Date: 2026-09-03 16:13:49.046118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aff938d3e38b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wells',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('well_name', sa.String(), nullable=False),
    sa.Column('location_code', sa.String(), nullable=True),
    sa.Column('asset_name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('well_type', sa.String(), nullable=True),
    sa.Column('target_depth', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('well_name')
    )
    op.create_table('daily_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('well_id', sa.Integer(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('source_filename', sa.String(), nullable=True),
    sa.Column('mode', sa.String(), nullable=True),
    sa.Column('present_depth', sa.Float(), nullable=True),
    sa.Column('day_meterage', sa.Float(), nullable=True),
    sa.Column('rb_start', sa.Date(), nullable=True),
    sa.Column('dr_start', sa.Date(), nullable=True),
    sa.Column('pt_start', sa.Date(), nullable=True),
    sa.Column('rb_days_planned', sa.Integer(), nullable=True),
    sa.Column('rb_days_actual', sa.Integer(), nullable=True),
    sa.Column('dr_days_planned', sa.Integer(), nullable=True),
    sa.Column('dr_days_actual', sa.Integer(), nullable=True),
    sa.Column('pt_days_planned', sa.Integer(), nullable=True),
    sa.Column('pt_days_actual', sa.Integer(), nullable=True),
    sa.Column('tot_days_planned', sa.Integer(), nullable=True),
    sa.Column('tot_days_actual', sa.Integer(), nullable=True),
    sa.Column('mud_weight', sa.Float(), nullable=True),
    sa.Column('mud_viscosity', sa.Float(), nullable=True),
    sa.Column('litho', sa.Text(), nullable=True),
    sa.Column('cost_planned_inr', sa.Float(), nullable=True),
    sa.Column('cost_actual_inr', sa.Float(), nullable=True),
    sa.Column('status_text', sa.Text(), nullable=True),
    sa.Column('oper_narrative', sa.Text(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['well_id'], ['wells.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('well_id', 'report_date')
    )
    op.create_table('proposals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('well_id', sa.Integer(), nullable=False),
    sa.Column('proposed_date', sa.Date(), nullable=True),
    sa.Column('approved_date', sa.Date(), nullable=True),
    sa.Column('approving_authority', sa.String(), nullable=True),
    sa.Column('afe_number', sa.String(), nullable=True),
    sa.Column('gto_reference', sa.String(), nullable=True),
    sa.Column('formation_tops', sa.Text(), nullable=True),
    sa.Column('mud_program', sa.Text(), nullable=True),
    sa.Column('casing_program', sa.Text(), nullable=True),
    sa.Column('objective', sa.Text(), nullable=True),
    sa.Column('planned_total_days', sa.Integer(), nullable=True),
    sa.Column('planned_total_cost_inr', sa.Float(), nullable=True),
    sa.Column('raw_extracted_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['well_id'], ['wells.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('well_id')
    )
    op.create_table('phase_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('daily_entry_id', sa.Integer(), nullable=False),
    sa.Column('phase_no', sa.Integer(), nullable=False),
    sa.Column('casing_size', sa.String(), nullable=True),
    sa.Column('depth_planned', sa.Float(), nullable=True),
    sa.Column('depth_actual', sa.Float(), nullable=True),
    sa.Column('days_planned', sa.Integer(), nullable=True),
    sa.Column('days_actual', sa.Integer(), nullable=True),
    sa.Column('hole_top', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['daily_entry_id'], ['daily_entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('repair_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('daily_entry_id', sa.Integer(), nullable=False),
    sa.Column('equipment_or_system', sa.String(), nullable=True),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.Column('confidence', sa.String(), nullable=True),
    sa.Column('reviewed', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['daily_entry_id'], ['daily_entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('repair_events')
    op.drop_table('phase_snapshots')
    op.drop_table('proposals')
    op.drop_table('daily_entries')
    op.drop_table('wells')
    # ### end Alembic commands ###
